# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron:  '25,55 * * * 1-5'

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run App
      env: 
        HRLOG_USERNAME: ${{ secrets.HRLOG_USERNAME }}
        HRLOG_PASSWORD: ${{ secrets.HRLOG_PASSWORD }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 app.py

